Traceback (most recent call last):
  File "benchmark_gpu.py", line 55, in <module>
    H, edges = pp.joint_pdf(w_norm, DI_c, bins=bins, ranges=ranges, log=False)
  File "/mnt/beegfs/home/allaglo/sfemans_ai/nikita/gpu_source/stats.py", line 122, in joint_pdf
    H, xedges, yedges = cp.histogram2d(field1, field2, bins=bins, range=ranges, \
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_statistics/histogram.py", line 502, in histogram2d
    hist, edges = histogramdd([x, y], bins, range, weights, density)
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_statistics/histogram.py", line 400, in histogramdd
    ncount = tuple(
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_statistics/histogram.py", line 402, in <genexpr>
    cupy.searchsorted(edges[i], sample[:, i], side='right')
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_sorting/search.py", line 422, in searchsorted
    return _searchsorted(a, v, side, sorter, True)
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_sorting/search.py", line 460, in _searchsorted
    y = cupy.zeros(v.shape, dtype=cupy.int64)
  File "/mnt/beegfs/home/allaglo/miniconda3/envs/statistics/lib/python3.8/site-packages/cupy/_creation/basic.py", line 211, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy/_core/core.pyx", line 136, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 224, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 742, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1419, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1440, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1120, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1141, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1379, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 4,684,915,200 bytes (allocated so far: 46,872,612,352 bytes).
